### ISSUE TITLE
Memory temperature

### ISSUE THREAD

**Issue by WMP** [jelmd/nvmex#1]
I thought this project could read the memory temperature, unfortunately for my RTX 3080 and RTX 3080 Ti it can't read the temperauta. The only program I know is nvtool from hiveos.

**Comment by jelmd** [comment]
Well, actually it depends on what the Nvidia management library (nvml) exposes (which in turn relies on the nvidia driver being used). Unfortunately we don't have RTX 3080* for testing. But I guess, Nvidia exposes memory temperature for high level GPUs, only. E.g. we use nvmex to monitor memory temperature beside other data on our V100s and A100s. But on our RTX 2080 Tis and A40s it is not exposed. So I do not wonder, that these data are not exposed on RTX 3080* as well. Anyway, since we do not overclock, having the GPU temperature + clocks and power draws is more than sufficient to operate them in a safe manner.

Wrt. nvtool: Yes, there might be some private undocumented functions/symbols in the NVML (or driver itself), which may reveal the required data (usually the API functions are usually wrappers around some lower level ones ...). However finding and maintaining such entry points is often really time consuming, pretty dirty (unstable) and more or less unreliable because undocumented. So if you have the source code, I can have a look at it, but I guess, they rely on dirty tricks to get this info.

**Comment by WMP** [comment]
Unfortunatelly i havent source ccode to nvtool or gminer (also show memory temperature). If you want to get RTX 30xx memory temperature, i can give you shell to my VM with this card, but this is 100% dirty hacks.
